name: Trigger auto deployment for container-app-2w4t4uvzcxlre

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-2w4t4uvzcxlre-AutoDeployTrigger-1b5705e5-34f0-4a22-99d1-07759752c78c.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPP2W4T4UVZCXLRE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPP2W4T4UVZCXLRE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPP2W4T4UVZCXLRE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPP2W4T4UVZCXLRE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPP2W4T4UVZCXLRE_REGISTRY_PASSWORD }}
          containerAppName: container-app-2w4t4uvzcxlre
          resourceGroup: todonodejspgsqlgoogleautha2fdb5ed
          imageToBuild: default/container-app-2w4t4uvzcxlre:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


